### ISSUE TITLE
如果能设置默认值就完美了

### ISSUE THREAD

**Issue by ppttv** [webCoderJ/ele-multi-cascader#1]

**Comment by webCoderJ** [comment]
是可以的，绑定的 `v-mode` 有值的话，初始化的时候会设置为默认值

**Comment by marinLu** [comment]
我引入了这个自定义指令  失去焦点还是隐藏不了这个弹框   有办法没

**Comment by webCoderJ** [comment]
> 我引入了这个自定义指令 失去焦点还是隐藏不了这个弹框 有办法没

请描述的清楚些，不太明白

**Comment by webCoderJ** [comment]
默认值设置问题已修复

**Comment by marinLu** [comment]
就是我现在有一个关联关系的问题  比如我最后一级就只有3条  我全部勾选之后能不能让我的二级默认勾选呢

**Comment by marinLu** [comment]
就是一个联动的问题   比如我选中第一级的一个  那么这个下边的二级三级都选中，有没有这样的方法

**Comment by webCoderJ** [comment]
你说的这种情况在每项都作为独立项时，交互逻辑是有问题的哈，其实是全选反选的问题，子项全选时他的父级到底是该被选中，还是不被选中呢？因为他的父级其实也是一个独立项。因此在逻辑上剔除了层级关系，级联只是作层级展示，把每个项都看做单项，都包含一个value。这样才不会有冲突。

**Comment by marinLu** [comment]
对  就是你说这个问题  我现在的需求是一个需要全选和反选展示  我这边刚才尝试改了一下你的代码  全选可以实现  就是这个反选现在还是不行  而且需要加很多的逻辑判断跟数据处理  你这边有好的思路吗 谢谢

**Comment by jerryqx** [comment]
你好,我现在也是需要全选和反选展示这样的功能,正在尝试修改你的代码.希望能提供些思路,谢谢

**Comment by webCoderJ** [comment]
> 还有一个问题想请教一下,我是通过复制源码的方式使用的.但是这个v-click-outside指令会报错Failed to resolve directive: click-outside.请问下改如何解决?

这个项目还依赖了 `v-click-outside` ,直接 npm install 就可以

**Comment by jerryqx** [comment]
> > 还有一个问题想请教一下,我是通过复制源码的方式使用的.但是这个v-click-outside指令会报错Failed to resolve directive: click-outside.请问下改如何解决?
> 
> 这个项目还依赖了 `v-click-outside` ,直接 npm install 就可以

我现在项目使用不是vue-cli方式构建的.就是通过<script>标签引入的vue和elementui.请问这样的有什么办法能解决么?

**Comment by webCoderJ** [comment]
> 你好,我现在也是需要全选和反选展示这样的功能,正在尝试修改你的代码.希望能提供些思路,谢谢

可以在 `checkedChange` 这个方法中去调用检测是否全选的方法，可以参照 `describeCheckedMap` 方法遍历全部项目，如果子项选中个数等于当前层级的children长度，给当前父项 checked 设置为 true 即可。有时间我可以提供这个选项，也欢迎PR，最近有点忙了，没时间搞 ^ ^ !

**Comment by webCoderJ** [comment]
> > > 还有一个问题想请教一下,我是通过复制源码的方式使用的.但是这个v-click-outside指令会报错Failed to resolve directive: click-outside.请问下改如何解决?
> > 
> > 
> > 这个项目还依赖了 `v-click-outside` ,直接 npm install 就可以
> 
> 我现在项目使用不是vue-cli方式构建的.就是通过<script>标签引入的vue和elementui.请问这样的有什么办法能解决么?

这个插件暂时没有提供打包，可以自己根据源码修改的~ 不过比较麻烦

**Comment by jerryqx** [comment]
> > 你好,我现在也是需要全选和反选展示这样的功能,正在尝试修改你的代码.希望能提供些思路,谢谢
> 
> 可以在 `checkedChange` 这个方法中去调用检测是否全选的方法，可以参照 `describeCheckedMap` 方法遍历全部项目，如果子项选中个数等于当前层级的children长度，给当前父项 checked 设置为 true 即可。有时间我可以提供这个选项，也欢迎PR，最近有点忙了，没时间搞 ^ ^ !

嗯 谢谢  已经按照你提供的思路基本改出来了
