### ISSUE TITLE
ClickOutside方法在点击其他select组件的时候无法触发

### ISSUE THREAD

**Issue by jkhaoqi110** [webCoderJ/ele-multi-cascader#11]
![gif](https://user-images.githubusercontent.com/7346148/51169418-cfd68d00-18e6-11e9-9bec-0afcd264ae07.gif)

点击其他select组件的时候无法自动关闭ele-multi-cascader组件的popover

**Comment by Aaminly** [comment]
import ClickOutside from 'element-ui/src/utils/clickoutside'
使用element内置的clickoutside可以解决该问题

**Comment by webCoderJ** [comment]
> import ClickOutside from 'element-ui/src/utils/clickoutside'
> 使用element内置的clickoutside可以解决该问题

嗯 已经解决
