### ISSUE TITLE
请问怎么只显示最后一级的数据

### ISSUE THREAD

**Issue by ZQW0709** [webCoderJ/ele-multi-cascader#13]
![image](https://user-images.githubusercontent.com/39164604/51299074-11d80e00-1a62-11e9-9880-532c0196ce26.png)
请问有个需求，就是怎么将还有子节点的数据不要加载到输入框

**Comment by webCoderJ** [comment]
![image](https://user-images.githubusercontent.com/19652730/51301215-5fa44480-1a69-11e9-88f9-6393beb566b9.png)
show-all-levels: false
