### ISSUE TITLE
是否有计划支持配置hover展开次级菜单

### ISSUE THREAD

**Issue by youngmings** [webCoderJ/ele-multi-cascader#16]
谢谢开发了这个组件！！
后期是否会支持配置为“hover”展示次级菜单？

**Comment by webCoderJ** [comment]
不好意思，这个暂时没有计划支持哈，可以手动修改源码实现，实现方法很简单的，看下就知道啦

**Comment by youngmings** [comment]
> 不好意思，这个暂时没有计划支持哈，可以手动修改源码实现，实现方法很简单的，看下就知道啦

好的^-^
