### ISSUE TITLE
在打包的时候报错。

### ISSUE THREAD

**Issue by Eliasxcl** [webCoderJ/ele-multi-cascader#19]
项目中安装插件，部署上线时，打包提示报错，

**Comment by Eliasxcl** [comment]
ERROR in Encountered an error while minifying static/js/app.44745371.js:
SyntaxError: Unexpected token: keyword (const)
  5463 |
  5464 |
> 5465 | const isServer = __WEBPACK_IMPORTED_MODULE_0_vue__["default"].prototype.$isServer;
  5466 |
  5467 | /* istanbul ignore next */
  5468 | const on = (function() {

 Build failed with errors.

我webpack打包配合了环境区分，猜测是是区分环境执行导致的，有没有遇到类似问题？

**Comment by webCoderJ** [comment]
这个错误应该和组建没啥关系哈，请检查一下webpack配置

**Comment by Eliasxcl** [comment]
感谢回复，我暂且复制使用了源码，打包部署未报错，效果正常。下一步再看看npm安装造成报错的问题

**Comment by wangwenjie1314** [comment]
![image](https://user-images.githubusercontent.com/4018406/55313488-7cfa8380-549a-11e9-9e8c-b769cd41acf7.png)
需要配置下 https://segmentfault.com/a/1190000009858385
