### ISSUE TITLE
输入框条数限制以和子选项单选有支持吗？

### ISSUE THREAD

**Issue by CodeDome** [webCoderJ/ele-multi-cascader#23]
输入框条数限制以和子选项单选的需求有支持吗？

**Comment by webCoderJ** [comment]
条数限制可自己修改disabled实现，单选一直都是支持的，不知道你说的具体是什么

**Comment by CodeDome** [comment]
条数限制是指选择以后的输入框中的值的个数限定，比如说最多能选多少个。单选支持是指在下拉后的二级子选项中本来是多个复选框，但是当选择其中一个以后其他几个就不能选择且状态变为禁选状态（也就是几个子选项只能选一个取消后恢复原先的状态）
