### ISSUE TITLE
v-model问题

### ISSUE THREAD

**Issue by wojiaoggyy** [webCoderJ/ele-multi-cascader#26]
过程： v-model绑定数组ARR，多选完成后，根据其他逻辑判断，删除了ARR最后一项；

问题： 选择框和下拉列表里的选中状态都未更新。

**Comment by Megatron0817** [comment]
是没有实现数据双向绑定的问题吗？

**Comment by webCoderJ** [comment]
这个是最基本的功能哈，肯定实现了的
