### ISSUE TITLE
移除的时候能不能拿到value

### ISSUE THREAD

**Issue by mschange** [webCoderJ/ele-multi-cascader#31]
比如 ，我现在移除北京。现在能拿到北京，但是在移除回调中，能不能拿到对应的code

![1553832159(1)](https://user-images.githubusercontent.com/36876310/55208860-d2c0f880-521a-11e9-9c5c-dec8e2192711.png)

**Comment by webCoderJ** [comment]
在移除事件中，第二个参数就是当前移出的子项，里面应该有你想要的信息
![image](https://user-images.githubusercontent.com/19652730/55223033-43323e80-5248-11e9-90cf-59d1624e8c98.png)

**Comment by mschange** [comment]
你说的第二个参数是我上面的value，还是哪里的第二个参数
