### ISSUE TITLE
选择器大小可控吗

### ISSUE THREAD

**Issue by luuuuuufei** [webCoderJ/ele-multi-cascader#32]
获取的数据有点长，展示不全，没有相应的show-overflow-tooltip，或者单独改变每个menu_item的长度大小

**Comment by CABOnly** [comment]
我也遇到了相同的问题，还有就是控件高度不可控

**Comment by webCoderJ** [comment]
> 我也遇到了相同的问题，还有就是控件高度不可控

你好，插件能提供的是一些基础的api，我不可能把所有的潜在功能都写一遍。比如高度，你可以通过覆盖class实现。

**Comment by luuuuuufei** [comment]
可以在页面中加style，覆盖默认的css。
