### ISSUE TITLE
ie兼容问题

### ISSUE THREAD

**Issue by 328174749** [webCoderJ/ele-multi-cascader#34]
我在ie11下项目报错,错误原因 语法错误

**Comment by 328174749** [comment]
请问你自己能够成功在ie11下运行么?  我是通过npm安装的您的插件,其实IE下错误能难定位,我是把您的插件引用在项目中注释掉,项目能够正常运行在ie下,才判断出来是你的插件问题

**Comment by webCoderJ** [comment]
这个问题已经定位到，稍后更新，请关注下~

**Comment by 328174749** [comment]
谢谢!!!

**Comment by 328174749** [comment]
更新了 炸了
![image](https://user-images.githubusercontent.com/17706077/55870513-5388d880-5bbb-11e9-85e4-f112693baa05.png)

**Comment by webCoderJ** [comment]
哈哈哈，写错了个东西，你再更新下吧

**Comment by 328174749** [comment]
2.2.2还是不行,同样错误

**Comment by webCoderJ** [comment]
应该是模块加载有问题，可以先复制代码到项目中使用，后续修复这个问题
