### ISSUE TITLE
为什么我引用了 但是不能显示？

### ISSUE THREAD

**Issue by liwenbin1988** [webCoderJ/ele-multi-cascader#36]
![image](https://user-images.githubusercontent.com/33473191/55710838-0f140600-5a1e-11e9-94c4-7fafc5fc05b0.png)
options里面也有数据 没有显示 
![image](https://user-images.githubusercontent.com/33473191/55710910-34a10f80-5a1e-11e9-86cc-22d89b224704.png)

**Comment by liwenbin1988** [comment]
option是这样的
![image](https://user-images.githubusercontent.com/33473191/55848855-0425b680-5b81-11e9-8d27-c287457aaa07.png)

**Comment by webCoderJ** [comment]
labelKey="title" 设置这个选项了吗

**Comment by liwenbin1988** [comment]
还想请教一下！就是我动态加载子集的时候 不能往下加载
![image](https://user-images.githubusercontent.com/33473191/56078562-33a41f80-5e1c-11e9-8fd8-bf147e58a0e5.png)
![image](https://user-images.githubusercontent.com/33473191/56078592-7108ad00-5e1c-11e9-8663-03c75fad103a.png)
![image](https://user-images.githubusercontent.com/33473191/56078597-7ebe3280-5e1c-11e9-8892-1e70ba142708.png)
![image](https://user-images.githubusercontent.com/33473191/56078599-88e03100-5e1c-11e9-927e-cb28be17af59.png)
