### ISSUE TITLE
单选多选可个性化配置

### ISSUE THREAD

**Issue by JILL1231** [webCoderJ/ele-multi-cascader#38]
比如：归属类需求，一般需要一级单选，二级多选

**Comment by webCoderJ** [comment]
可以通过disabled去实现哦，归类的需求需要你自己实现。

**Comment by JILL1231** [comment]
还有个问题，代码跑起来一直报

Error in callback for watcher "casTree": "TypeError: Cannot read property 'style' of undefined"

Cannot read property 'style' of undefined

错误

**Comment by webCoderJ** [comment]
> 还有个问题，代码跑起来一直报
> 
> Error in callback for watcher "casTree": "TypeError: Cannot read property 'style' of undefined"
> 
> Cannot read property 'style' of undefined
> 
> 错误

已修复，更新下试试
