### ISSUE TITLE
数据量多的时候，会出现如下问题

### ISSUE THREAD

**Issue by JILL1231** [webCoderJ/ele-multi-cascader#40]
![image](https://user-images.githubusercontent.com/11407881/55866683-6f887c00-5bb3-11e9-9b6d-cbfbb0956db2.png)
 
两层级的数据变为一层级的，同时，UI也会出现问题

**Comment by webCoderJ** [comment]
额，不是有滚动条吗.. 你到底是在啥环境调试的 -_-

**Comment by JILL1231** [comment]
Vue  element

**Comment by JILL1231** [comment]
有二级的时候，点击，二级的数据会跑到一级的数据里来
