### ISSUE TITLE
火狐浏览器控制台报警告导致展开子菜单失败，谷歌一切正常

### ISSUE THREAD

**Issue by Megatron0817** [webCoderJ/ele-multi-cascader#41]
![image](https://user-images.githubusercontent.com/39528323/55936834-031c8400-5c6a-11e9-88ca-0ed935c21764.png)

**Comment by Megatron0817** [comment]
![image](https://user-images.githubusercontent.com/39528323/55936775-d49ea900-5c69-11e9-932f-3603c244889d.png)

**Comment by Megatron0817** [comment]
![image](https://user-images.githubusercontent.com/39528323/55936914-37904000-5c6a-11e9-9ab0-03a9a63e101f.png)

**Comment by Megatron0817** [comment]
![image](https://user-images.githubusercontent.com/39528323/55937057-98b81380-5c6a-11e9-829c-289cb1f410e6.png)

**Comment by Megatron0817** [comment]
![image](https://user-images.githubusercontent.com/39528323/55944741-d1141d80-5c7b-11e9-9bae-a8c6f7b458ab.png)
我把这个判断去掉就可以了=.=，但是这么改又不太好，不知道具体原因是什么，还望大佬指教！

**Comment by webCoderJ** [comment]
已修复，可更新使用
