### ISSUE TITLE
在项目中怎么复制源码使用啊

### ISSUE THREAD

**Issue by dat126** [webCoderJ/ele-multi-cascader#45]

**Comment by dat126** [comment]
没怎么用过webpack下的开发  这问题太蠢了  已经弄好了

**Comment by dat126** [comment]
请问动态加载子项 这里是怎么把数据放到子项内，返回的Promise这个对象是什么意思


------------------ 原始邮件 ------------------
发件人: "彭杰"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 上午10:40
收件人: "webCoderJ/ele-multi-cascader"<ele-multi-cascader@noreply.github.com>;
抄送: "Dong_at"<1269437868@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [webCoderJ/ele-multi-cascader] 在项目中怎么复制源码使用啊 (#45)




Closed #45.

**Comment by webCoderJ** [comment]
可以参考一下demo代码
