### ISSUE TITLE
label名称长度问题

### ISSUE THREAD

**Issue by DemoHu** [webCoderJ/ele-multi-cascader#46]
作者在源码中将witdh 写死在了160px 导致如果label长度大于160 会被忽略掉，我将你的源码中这段css删除后可以正常显示完成的label了，但是发现当展开三级之后，还是会因为label过长导致样式错位
后来发现您源码中动态改变菜单宽度的代码
`// 改变菜单宽度
    setPopperWidth() {
      let width = (160 + 1) * this.casTree.length;
      document.getElementsByClassName(this.classRef)[0].style.width = width + "px";
    }`

源码中 设置了   ` .cascader-popper {width:100%} `

我尝试将这些代码删除，解决了这个问题

不知道作者当初设置这些代码的原因是什么
这里依然是基于160 * 子菜单个数算的，这依然限制了面板的长度，导致错位了，请问作者对这个问题怎么解决
![Snipaste_2019-04-17_14-37-57](https://user-images.githubusercontent.com/26042365/56266288-6a30b180-611e-11e9-91e1-c2e882fa4e52.png)

**Comment by DemoHu** [comment]
建议删除 main.vue 中的  
```
setPopperWidth() {
      let width = (160 + 1) * this.casTree.length;
      let el = document.getElementsByClassName(this.classRef)[0];
      if(el){
        el.style.width = width + "px";
      }
    }
```
```
.cascader-popper {
  width: 100%;
}
```
```
.cascader-menu {
  width: 160px !important;
}
```

**Comment by webCoderJ** [comment]
已经修复，可更新使用
