### ISSUE TITLE
请问如何默认展示下拉菜单呢？而不是触发input

### ISSUE THREAD

**Issue by msisliao** [webCoderJ/ele-multi-cascader#56]
想默认展示下拉菜单，没有input
还有就是如何默认展示所有层级呢，不是点击触发下一级

**Comment by webCoderJ** [comment]
![image](https://user-images.githubusercontent.com/19652730/57353769-26b8e880-719c-11e9-9046-ddf925783774.png)
可以调用这个方法，传入 true
