### ISSUE TITLE
第三次给model赋值，显示不会变，很奇怪的问题

### ISSUE THREAD

**Issue by decadestory** [webCoderJ/ele-multi-cascader#7]
每个人不一样的城市，第一个点明细，城市 显示 正常，第一次也正常，第三次，输入框的文字还是第二次那个文字。不知道你有没有遇到过这问题

**Comment by webCoderJ** [comment]
属于同一个问题哈，https://github.com/webCoderJ/ele-multi-cascader/issues/5
